language: node_js

node_js:
  - "4"

addons:
  firefox: "50.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphicsmagick
      - g++-4.8

env:
  global:
    - DISABLE_ROUTE_LOGGING=true
    - DISABLE_CLIENT_METRICS_STDERR=true
    - CXX=g++-4.8

sudo: false

cache:
  directories:
    - node_modules
    - app/bower_components
    - deps/node_modules/fxa-auth-server/node_modules
    - deps/node_modules/fxa-profile-server/node_modules
    - deps/node_modules/fxa-oauth-server/node_modules

notifications:
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

before_install:
  # Setup the xvfb environment. Read more at http://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  # install everything for full dev in the fxa-content-server.
  - travis_retry npm install --silent
  - npm ls --depth 0 | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g'
  - grunt lint
  # copy over the configuration that can be used to start the server.
  - cp server/config/local.json-dist server/config/local.json
  # install auth, oauth, verifier and profile servers
  - ./tests/ci/deps.sh
  - npm start &
  - sleep 5

# now run the tests!
script:
  - travis_retry grunt nsp # check for vulnerable modules via nodesecurity.io
  - grunt selectconfig:dist l10n-generate-pages &> /dev/null
  - grunt htmllint:dist
  - which firefox
  - firefox --version
  # even though Firefox <version> is install in `addons`,
  # the default firefox-bin is used by Selenium, which is Firefox 31.
  # firefoxBinary=`which firefox` forces the version we installed
  # to be used.
  - travis_retry npm run test-travis firefoxBinary=`which firefox`
  - travis_retry npm run test-server
